### ISSUE TITLE
Error in Composer dependencies / incompatibility with `symfony/security-core`

### ISSUE THREAD

**Issue by ThomasLandauer** [doctrine/persistence#140]
I think there's something wrong with composer dependencies somewhere. I can't tell you the exact source - I can only tell you what I've observed:

In the beggining, I have this in my `composer.json` (only showing `doctrine/*` and `symfony/security-*`):
```json
"doctrine/annotations": "^1.8",
"doctrine/dbal": "^2.12",
"doctrine/orm": "^2.7",
"symfony/security-bundle": "4.4.*",
```
...and this is contained in the output of `composer show`:
```
doctrine/persistence  1.3.8
symfony/security-core v4.4.15
```

Now, if I add `"symfony/security-core": "4.4.*",` to `composer.json` and run `composer update`, this happens:

```bash
Lock file operations: 0 installs, 3 updates, 1 removal
  - Removing doctrine/reflection (1.2.1)
  - Upgrading doctrine/common (2.13.3 => 3.0.2)
  - Upgrading doctrine/persistence (1.3.8 => 2.1.0)
  - Downgrading symfony/orm-pack (v1.2.0 => v1.1.0)
```
(which breaks my project, due to https://stackoverflow.com/q/63688919/1668200)

But then, if I also add `"doctrine/persistence": "^1.3",` to `composer.json` and run `composer update`, the downgrade is magically undone:
```bash
Lock file operations: 1 install, 3 updates, 0 removals
  - Downgrading doctrine/common (3.0.2 => 2.13.3)
  - Downgrading doctrine/persistence (2.1.0 => 1.3.8)
  - Locking doctrine/reflection (1.2.1)
  - Upgrading symfony/orm-pack (v1.1.0 => v1.2.0)
```

**Comment by greg0ire** [comment]
Your project depends on `doctrine/persistence` since you `use Doctrine\Persistence\ManagerRegistry;`, yet it does not appear in your `composer.json`. You need to fix this otherwise you are going to have a lot of other weird bugs in the future. You should check your project with https://github.com/maglnet/ComposerRequireChecker

**Comment by ThomasLandauer** [comment]
> You should check your project with https://github.com/maglnet/ComposerRequireChecker

This is exactly what I did yesterday ;-) And fixing everything else went smoothly - except this issue.

So the question remains: Why are those 4 Doctrine packages getting nervous, when I add an unrelated Symfony package *which I already have*?

Please reopen.

**Comment by greg0ire** [comment]
> This is exactly what I did yesterday

So you do have `doctrine/persistence` in your `composer.json`?

**Comment by ThomasLandauer** [comment]
See first comment: In the beginning not, and everything was fine. Then adding `symfony/security-core` broke it. Then adding `doctrine/persistence` fixed it.

I understand what you're saying ("You need to have `doctrine/persistence` in there, since you're actually using it"). But the same applies to `symfony/security-core`! So why is Doctrine breaking, if I just happen to fix the `symfony/security-core` dependency?

**Comment by greg0ire** [comment]
> So why is Doctrine breaking, if I just happen to fix the symfony/security-core dependency?

Because you allowed Doctrine to be a moving part. By not constraining it, you explicitly said that you don't care if you are using v 42 or 346. You then cannot complain when things break because you coded against a specific version, can you?

Closing again, since the contract you have with Doctrine and any dependency you have is you can't complain about BC-breaks if you let Composer change the version in major way to satisfy other constraints you give to it. And yes, changing seemingly unrelated dependencies might cause Composer to upgrade or downgrade Doctrine. If you don't care, don't ask why, if you do care, use constraints.

**Comment by ThomasLandauer** [comment]
Thanks for your patience, but you still can't convince me that this is "normal" behavior. However, you did convince me that it's not a Doctrine issue :-) - so I opened an issue at composer.
