### ISSUE TITLE
Use `@no-named-parameters` in interfaces

### ISSUE THREAD

**Issue by franmomu** [doctrine/persistence#187]
Triggered by https://github.com/doctrine/mongodb-odm/pull/2315#issuecomment-848313449

Using the latest version (4.7.3) of `vimeo/psalm` makes psalm fail [when a method overrides a parent method but renames a parameter](https://psalm.dev/docs/running_psalm/issues/ParamNameMismatch/) because it could fail when using PHP 8 named parameters.

[Renaming parameters could be BC break](https://github.com/doctrine/mongodb-odm/pull/2315#issuecomment-847253049), so @malarzm suggested to add [`@no-named-arguments`](https://github.com/Roave/BackwardCompatibilityCheck/issues/264) to some of the public API.

We could add them for example in https://github.com/doctrine/persistence/blob/70d7177779d4ff6e31f269169bc5c919de1bf7d7/lib/Doctrine/Persistence/ObjectManager.php, but I guess this should be decided internally to use it or not.

**Comment by alcaeus** [comment]
I'm against this change. While we currently have some discrepancies regarding argument names, I'm of the opinion that the variable name is part of the API and should thus also be usable in named arguments. Consider the following change:
```diff
-    public function doSomething(string $filename);
+    public function doSomething(string $filenameOrPath);
```

Named arguments would make this a BC break, but I'll argue that this was a BC break before already, we just didn't care: the parameter name indicated that you'll receive a file name, now all of a sudden you're also expected to expect a path. Compare with the following API that uses distinct types:
```diff
     interface File extends FileSystemElement {}

-    public function doSomething(File $item);
+    public function doSomething(FileSystemElement $item);
```

Yes, named args make it more difficult to rename method arguments, and we should find a solution for that. However, in a package such as this, where the core value is provided from interfaces, we should make argument names part of the public API and avoid changing them. In the end, it will lead to a cleaner API changes (e.g. deprecating a method and introducing a new method) when things change.

There's another reason why I'm against blanket `no-named-parameters` statements: the adoption of such a feature depends on how much of the ecosystem works with it. If I have to continuously think "does this library support named arguments?" before writing calls, then I'm very inclined to not use them at all. Since I believe they can make code cleaner, make APIs cleaner, and make API changes more explicit, my goal is to encourage people to use them, not the other way around.

**Comment by greg0ire** [comment]
I'd rather we go through the BC-break as a "woops we forgot this before allowing PHP 8" rather than to wait for more people to actually use them. IMO it's reasonable to assume there are very few people actually calling us like that today.

**Comment by malarzm** [comment]
My reasoning for using `no-named-parameters` is that our interfaces (take https://github.com/doctrine/persistence/blob/3.0.x/lib/Doctrine/Persistence/ObjectManager.php as an example) are rather simple with just few required parameters. I see no value at all in using `$om->persist(object: $user)` or `$om->find(class: User::class, id: $id)`. Places where I do see named arguments shine are methods full of optional arguments, where you'd need to pass 2 default values just to set something different for 3rd one. This is not the case in our APIs thus named arguments will provide little to no value for our end users, while forcing us to think about an additional place where it's possible to break BC.

While talking about this internally @alcaeus had a bright idea to support named arguments but just for optional arguments. I believe this would be a good compromise and the one we should really explore :)

**Comment by franmomu** [comment]
We've been changing the parameter names, so there is no need for this anymore :)
