### ISSUE TITLE
Annotations are not carried from document to proxy

### ISSUE THREAD

**Issue by josefsabl** [doctrine/persistence#20]
Annotations in ODM documents methods are ignored by annotation reader because proxy does not carry the annotations from document class. Is this a bug or a feature? And what to do about it?

**Comment by Ocramius** [comment]
Annotations are to be read from the source classes: the annotation reader is only triggered against the original entity/document class.

**Comment by josefsabl** [comment]
> Annotations are to be read from the source classes: the annotation reader is only triggered against the original entity/document class.

Well, I certainly have a case where reader tries to read my custom annotations from proxy class. It is a custom annotation and custom functionality, yes. But the way proxies work is not transparent at all. There are cases where I get the original document and there are cases where I get proxy depending on context and I do not have it under control. And annotations just stop working.

**Comment by Ocramius** [comment]
> Well, I certainly have a case where reader tries to read my custom annotations from proxy class. 

Then something is probably wrong in the metadata loading.

This bit makes sure that a parent class is checked, if you are currently giving a proxy class name to it: https://github.com/doctrine/persistence/blob/1ff4ce45de684a10a671fba3766fbc77b31abd30/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php#L165

**Comment by josefsabl** [comment]
Okay, thanks for the direction, will take a look at it.

**Comment by alcaeus** [comment]
@josefsabl I’m not following, is this library looking up metadata for a proxy or yours? Is this even related to metadata loading or is it purely a custom implementation of annotations?

**Comment by josefsabl** [comment]
No, I don't think this is related to metadata loading. I'll try to describe again, sorry for not being clear :-)

We use Doctrine ODM, so our documents are persisted to MongoDB etc...

And unrelated to this we use Doctrine\Annotations to annotate our documents for some custom features, e.g. validation, form generation from documents etc. And these features are completely unrelated to persisting documents to database.

But then I have a function like this:

```
function doGenerateForm(MyDocument $document) {
   $annotation = $this->reader->getMethodAnnotation(...);
   //$annotation is null here, because $document is not MyDocument but proxy and proxy did strip away those annotations.
}
```

**Comment by alcaeus** [comment]
Ah. This isn't related to the persistence library then.

Since the annotation reader is not supposed to know of proxies, you'll have to resolve this yourself: when you're reading annotations for a class, you need to make sure that you're passing the correct class name. For MongoDB ODM 1.x, you can use the `ClassUtils` class from `doctrine/common` to get the real class name, then create the necessary reflection objects beginning with that class name and passing those to the annotation reader. Note that any handling of classes extending another classes will have to be dealt with manually (as is done in the metadata reader) since there may be annotations on private members which won't be available in extending classes.

**Comment by Ocramius** [comment]
Yeah, you'll need to get the real class there: annotations are specifically designed to *NOT* be inherited, and proxies won't copy annotations anyway, as that may change the semantics of the application (you now have duplicate configs, once in an artifact, once in a source class).

Closing here: please use the same approach I linked here.

**Comment by Ocramius** [comment]
> And proxies should be designed in a way that they can be used in place of real classes.

Static information cannot be replicated on proxies. Having two classes with the same `@Table(name="foo")` (just an example) in a codebase will just lead to other processes to crash. In addition to that, remember that the annotation is always bound to the `ReflectionClass` it comes from, and you really shouldn't do anything with the `get_class($aProxy)`:

 1. because it's a gibberish string
 2. because it is a generated artifact, so no other code knows about it, except for the portions responsible for its existence
