### ISSUE TITLE
Registry::getManagerForClass doesn't work with anonymous classes

### ISSUE THREAD

**Issue by Pierstoval** [doctrine/persistence#24]
### Situation:

* PHP 7.1.5
* Using windows (it's an important part)
* Trying to use Symfony validator to validate anonymous class

The validator point is useless, but what's triggered behind is the<br>`$registry->getManagerForClass(get_class($myAnonymousClassInstance));`

### The test

```php
$a = new class {
    public $value;
};

var_dump(get_class($a));

$manager = $this->getDoctrine()->getManagerForClass(get_class($a));
```` 

Output on Windows:

`class@anonymous\x00E:\dev\www\skeleton\src\AppBundle\Controller\DefaultController.php000001982329027F` 

With this, I get an `ORMException`:

```
Unknown Entity namespace alias 'class@anonymousE'.
```

Obviously, because there is the `:` syntax, Doctrine is looking for a specific entity namespace.

---

I also tested this on linux inside a command and it works:

```php
$a = new class {
    public $value;
};

$manager = $this->getContainer()->get('doctrine')->getManagerForClass(get_class($a));

var_dump($class, $manager);
```

Output is correct because `$manager` is `null`:

```
"class@anonymous\x00/mnt/e/dev/www/skeleton/src/AppBundle/Command/TestCommand.php0x7f66b1aa5341"
null
```

### The fix

I think the `AbstractManagerRegistry::getManagerForClass()` should return `null` if the class name starts with `class@anonymous\x00`, whatever the platform, because it is the way PHP 7.1 handles anonymous classes names.

What do you think?

**Comment by ZhukV** [comment]
Related to https://github.com/symfony/symfony/issues/38008

Anonymous classes contain `:` char, and system try to get real class with namespace used.

**Comment by greg0ire** [comment]
Let's have a look at the phpdoc comment for the parameter of `getMetadataFor`:

https://github.com/doctrine/persistence/blob/ebb6c322b4b438e4156523dafca1aedb1342353a/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php#L146

You are supposed to pass a class _name_ . _Anonymous_ classes don't have one, that's why they are called anonymous. 
I'm not sure why `get_class` returns a string in that case, when it could throw instead… anyway it's just a string representation of the anonymous class, but it can't be a name because of what I stated above.

The expected behavior would be to throw an exception, which is already what happens, so there is no bug.

But I suppose you didn't do that call yourself, but through `doctrine/orm`, which is where the bug should be reported (with a stack trace please).

**Comment by Pierstoval** [comment]
>  I'm not sure why `get_class` returns a string in that case, when it could throw instead… anyway it's just a string representation of the anonymous class, but it can't be a name because of what I stated above.

`get_class()` returns a string because even if it's an anonymous class, we can still use the Reflection API in order to get its details and metadata (so a string returned by `get_class()` is mandatory, even for anonymous ones).
I still think the ORM should return `null` in such case and not throw.

Do you recommend me to repost the issue on `doctrine/orm` then?

**Comment by greg0ire** [comment]
>  I still think the ORM should return null in such case and not throw.

Agreed.

> Do you recommend me to repost the issue on doctrine/orm then?

You can instead edit it to add a stack trace, and after you do I can use the "transfer issue" feature :slightly_smiling_face:

**Comment by MatTheCat** [comment]
Just discovered this one :sweat_smile: 

```
Doctrine\ORM\Exception\UnknownEntityNamespace:
Unknown Entity namespace alias "App\Domain\Command\CommandInterface@anonymous/srv/src/Controller/RegisterCustomerController.php"

  at vendor/doctrine/orm/lib/Doctrine/ORM/Exception/UnknownEntityNamespace.php:13
  at Doctrine\ORM\Exception\UnknownEntityNamespace::fromNamespaceAlias('App\\Domain\\Command\\CommandInterface@anonymous' . "\0" . '/srv/src/Controller/RegisterCustomerController.php')
     (vendor/doctrine/orm/lib/Doctrine/ORM/Configuration.php:227)
  at Doctrine\ORM\Configuration->getEntityNamespace('App\\Domain\\Command\\CommandInterface@anonymous' . "\0" . '/srv/src/Controller/RegisterCustomerController.php')
     (vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:726)
  at Doctrine\ORM\Mapping\ClassMetadataFactory->getFqcnFromAlias('App\\Domain\\Command\\CommandInterface@anonymous' . "\0" . '/srv/src/Controller/RegisterCustomerController.php', '24$101')
     (vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php:238)
  at Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor('App\\Domain\\Command\\CommandInterface@anonymous' . "\0" . '/srv/src/Controller/RegisterCustomerController.php:24$101')
     (vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:307)
  at Doctrine\ORM\EntityManager->getClassMetadata('App\\Domain\\Command\\CommandInterface@anonymous' . "\0" . '/srv/src/Controller/RegisterCustomerController.php:24$101')
     (vendor/symfony/doctrine-bridge/PropertyInfo/DoctrineExtractor.php:214)
  at Symfony\Bridge\Doctrine\PropertyInfo\DoctrineExtractor->getMetadata('App\\Domain\\Command\\CommandInterface@anonymous' . "\0" . '/srv/src/Controller/RegisterCustomerController.php:24$101')
     (vendor/symfony/doctrine-bridge/PropertyInfo/DoctrineExtractor.php:46)
  at Symfony\Bridge\Doctrine\PropertyInfo\DoctrineExtractor->getProperties('App\\Domain\\Command\\CommandInterface@anonymous' . "\0" . '/srv/src/Controller/RegisterCustomerController.php:24$101', array())
     (vendor/symfony/property-info/PropertyInfoExtractor.php:110)
  at Symfony\Component\PropertyInfo\PropertyInfoExtractor->extract(object(RewindableGenerator), 'getProperties', array('App\\Domain\\Command\\CommandInterface@anonymous' . "\0" . '/srv/src/Controller/RegisterCustomerController.php:24$101', array()))
     (vendor/symfony/property-info/PropertyInfoExtractor.php:50)
  at Symfony\Component\PropertyInfo\PropertyInfoExtractor->getProperties('App\\Domain\\Command\\CommandInterface@anonymous' . "\0" . '/srv/src/Controller/RegisterCustomerController.php:24$101')
     (vendor/symfony/validator/Mapping/Loader/PropertyInfoLoader.php:53)
  at Symfony\Component\Validator\Mapping\Loader\PropertyInfoLoader->loadClassMetadata(object(ClassMetadata))
     (vendor/symfony/validator/Mapping/Loader/LoaderChain.php:54)
  at Symfony\Component\Validator\Mapping\Loader\LoaderChain->loadClassMetadata(object(ClassMetadata))
     (vendor/symfony/validator/Mapping/Factory/LazyLoadingMetadataFactory.php:102)
  at Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory->getMetadataFor(object(CommandInterface@anonymous))
     (vendor/symfony/validator/Validator/RecursiveContextualValidator.php:307)
  at Symfony\Component\Validator\Validator\RecursiveContextualValidator->validateObject(object(CommandInterface@anonymous), '', array('Default'), 1, object(ExecutionContext))
     (vendor/symfony/validator/Validator/RecursiveContextualValidator.php:139)
  at Symfony\Component\Validator\Validator\RecursiveContextualValidator->validate(object(CommandInterface@anonymous), null, array('Default'))
     (vendor/symfony/validator/Validator/RecursiveValidator.php:97)
  at Symfony\Component\Validator\Validator\RecursiveValidator->validate(object(CommandInterface@anonymous), null, null)
     (vendor/symfony/validator/Validator/TraceableValidator.php:67)
  at Symfony\Component\Validator\Validator\TraceableValidator->validate(object(CommandInterface@anonymous))
     (src/CommandBus.php:28)
  at App\CommandBus->handle(object(CommandInterface@anonymous))
     (src/Controller/RegisterCustomerController.php:24)
  at App\Controller\RegisterCustomerController->__invoke(object(Request), object(RegisterCustomerMapper), object(CommandBus))
     (vendor/symfony/http-kernel/HttpKernel.php:152)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/srv/vendor/autoload_runtime.php')
     (public/index.php:5)
```

<dl>
<dt>doctrine/persistence</dt><dd>2.4.1</dd>
<dt>doctrine/orm</dt><dd>2.11.2</dd>
<dt>symfony/doctrine-bridge</dt><dd>6.0.7</dd>
</dl>

In my case `Symfony\Bridge\Doctrine\PropertyInfo\DoctrineExtractor` seems to be the culprit :thinking: 

Edit: https://github.com/symfony/symfony/pull/42603

**Comment by greg0ire** [comment]
You should probably ask that the sf issue be reopened, or even send a patch

**Comment by stof** [comment]
Well, the Symfony PR got closed because the author abandoned it without finishing the work. So just asking to reopen it will bring you nowhere. We need someone to actually finish the work and send a PR that can be merged.

**Comment by MatTheCat** [comment]
Indeed I opened https://github.com/symfony/symfony/issues/46105 after discovering the PR did not fix all the issues I encountered. When I’ll understand what could be done I’ll open one myself.

**Comment by MatTheCat** [comment]
Here’s the updated PR: https://github.com/symfony/symfony/pull/46111

**Comment by greg0ire** [comment]
Apologies, I see that it was a PR, not an issue indeed. Also I see that a Doctrine API is mentioned as a way to address this (`isTransient`), so maybe something can be done in this package to throw a more precise exception. It's hard for me to give this more thought right now because I'm on my phone, but feel free to beat me to it.

**Comment by stof** [comment]
@greg0ire in PHP, all classes have a name, even anonymous classes (so `get_class($object)` is always non-empty). To simplify the life of consumers of doctrine/persistence, I think we should handle them gracefully. Instead of failing in weird ways for them, we should trigger the proper MappingException telling there is no metadata (or return `true` in the case of `isTransient`). This way, callers don't need to make a special case for anonymous classes when they want to try to get metadata for an arbitrary object.

**Comment by greg0ire** [comment]
The docs do say `get_class` returns the name of the class of an object, so I guess as weird as it sounds, anonymous classes do have a name in PHP :sweat_smile: . . I should have paid more attention to the comments above, which already pointed that out.

> or return `true`

Did you mean `null`? Since we already return that on Linux, it would make sense to be consistent with that on Windows.

Note that there seem to be several issues here, one while getting class metadata, the other while attempting to get a manager. And while `ManagerRegistry::getManagerForClass()` has a nullable return type, `ClassMetadataFactory::getManagerForClass()` doesn't. But anyway, if we made it `nullable`, there would still need to be a null check and thus a special case in client code, wouldn't there be? In Symfony, I see that the metadata retrieval is wrapped in a private method that returns `null` in such cases: https://github.com/symfony/doctrine-bridge/blob/b2f04ccbaf624f2c154be45845959bdcf34de259/PropertyInfo/DoctrineExtractor.php#L211-L218, but the 2 call sites of that private method come with a `null` check: https://github.com/symfony/doctrine-bridge/blob/b2f04ccbaf624f2c154be45845959bdcf34de259/PropertyInfo/DoctrineExtractor.php#L46-L48
https://github.com/symfony/doctrine-bridge/blob/b2f04ccbaf624f2c154be45845959bdcf34de259/PropertyInfo/DoctrineExtractor.php#L201

Maybe we could use https://www.php.net/manual/en/reflectionclass.isanonymous.php to implement throwing an exception: https://www.php.net/manual/en/reflectionclass.isanonymous.php ?

**Comment by greg0ire** [comment]
Note that the feature that causes this bug, short aliases, is removed in `doctrine/persistence` 3.0, so in case you need a workaround until this is fixed, upgrading to 3.0 might be it.

**Comment by MatTheCat** [comment]
@stof would #286 obsolete https://github.com/symfony/symfony/issues/46105 and https://github.com/symfony/symfony/pull/46111 ?

**Comment by stof** [comment]
@MatTheCat I think it will indeed obsolete them.

**Comment by stof** [comment]
> Did you mean `null`? Since we already return that on Linux, it would make sense to be consistent with that on Windows.

@greg0ire this comment looks weird. `isTransient` returns a boolean.

**Comment by greg0ire** [comment]
OK I thought you meant to govern the return type of getMetadataFor with the return value of isTransient, I see what you actually meant now

**Comment by derrabus** [comment]
Can we close this issue now that #286 has been merged?
