### ISSUE TITLE
Prepended backslash in class name reloads the full metadata from scratch

### ISSUE THREAD

**Issue by Tofandel** [doctrine/persistence#300]
### Bug Report

Follow up of https://github.com/symfony/symfony/issues/46837

#### Summary

When extracting class metadata, doctrine copies the original class data and caches it only the first time
But following that copy, calls to `addEntityListener` are made which are not repercuted on the alias https://github.com/doctrine/persistence/blob/25ec98a8cbd1f850e60fdb62c0ef77c162da8704/src/Persistence/Mapping/AbstractClassMetadataFactory.php?rgh-link-date=2022-07-04T14%3A09%3A36Z#L180

#### Solution

~~The alias should not be copied, but should just be added to an alias map to retrieve the original cached class straight away~~

**Comment by stof** [comment]
Another alternative would be to assign the metadata to the alias, but as a PHP reference rather than a copy.

**Comment by Tofandel** [comment]
Well I think that's already the case because it's an EntityMetaData instance being copied
After looking at it a bit more, it's not this line that copies it, it's actually treated as a completely different class and reloaded, hence the issue
`getRealClass` doesn't remove this prepended slash

So I think it's just a question of trimming this slash in getRealClass, so that it's treated as an alias instead of reloaded from scratch

**Comment by greg0ire** [comment]
Normalization seems more like the way to go yes. If I understood correctly, all this is caused because `A\Class` and `\A\Class` are equally valid ways to refer to a class. If that's indeed the issue then we should tweak our APIs so that they normalize FQCNs passed as input to just one representation.

**Comment by greg0ire** [comment]
Also, be careful when talking about aliases because in `doctrine/persistence`, (short) aliases mean a representation like this: `My:Alias`. That feature has been deprecated in https://github.com/doctrine/persistence/pull/205

**Comment by Tofandel** [comment]
@greg0ire Yes exactly that

I think just this should cover it
```php
    public function resolveClassName(string $className): string
    {
        $className = ltrim($className, '\\');
        \\...
        
```

Yes sorry I used alias as in class_alias, but that's not really what I'm trying to depict either, so let's completely forget about aliases as they're not relevant to this, it's 100% a FQCN with multiple possible representation issue

**Comment by greg0ire** [comment]
Would it? 

I think that wouldn't be enough to take advantage of this cache here: https://github.com/doctrine/persistence/blob/25ec98a8cbd1f850e60fdb62c0ef77c162da8704/src/Persistence/Mapping/AbstractClassMetadataFactory.php?rgh-link-date=2022-07-04T14%3A09%3A36Z#L164-L166

If you call `getMetadataFor` with a class name prepended with a backslash, I'd expect this condition to always fail because I would expect `loadedMetadata` to use normalized class names (meaning without a leading backslash) as keys.

**Comment by Tofandel** [comment]
It would take advantage of the cache on line 180 just a bit after, otherwise we can ltrim straight away `$className` first thing in this function

Do you know any other places where class names would be used as keys?

**Comment by greg0ire** [comment]
> we can ltrim straight away $className first thing in this function

That would make a lot more sense to me.

> Do you know any other places where class names would be used as keys?

That normalization should also happen in `setMetadataFor` and `hasMetadataFor` IMO.
