### ISSUE TITLE
Doctrine\Common\Persistence\Mapping\MappingException  does not exist

### ISSUE THREAD

**Issue by Pasuvan** [doctrine/persistence#65]
Message: "Class 'Abcd\AppBundle\Entity\Market' does not exist" exception" => 
vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/MappingException.php.
Please help me.

**Comment by malarzm** [comment]
Well, the class can not be found `Abcd\AppBundle\Entity\Market`, the exception clearly states that. Maybe it can't be autoloaded due to typos/case-sensitivity. As it's currently written it's impossible to tell you more. Also please use StackOverflow or our Slack channel to get help with your app-related problems.
