### ISSUE TITLE
Exception: Target ManagerRegistry is not instantiable

### ISSUE THREAD

**Issue by fsasvari** [doctrine/persistence#85]
Hi there!

I'm getting a weird error when I updated the package to version "1.3.3". Working with Laravel 6 version and Doctrine, tried to do the `composer update` and getting the following error:

`Illuminate\Contracts\Container\BindingResolutionException  : Target [Doctrine\Persistence\ManagerRegistry] is not instantiable while building [App\Console\Commands\SomeCommand, App\Support\EntityManager].`

In my `construct()` method I inject the `Doctrine\Common\Persistence\ManagerRegistry` class. When I downgrade to version "1.2.0" everything works fine. Any help with this? Thank you!

**Comment by alcaeus** [comment]
The stack trace should show what is trying to instantiate that class - please report this error to that library instead. I'm not very familiar with Laravel and how they use the persistence library, but you may want to create an issue at https://github.com/laravel/framework/issues and cross-reference this issue here.

In particular, the `Doctrine\Persistence\ManagerRegistry` and `Doctrine\Common\Persistence\ManagerRegistry` interfaces are the same, except that the latter is deprecated.

**Comment by fsasvari** [comment]
Yeah, but the problem is because 1.2.0 version works, but 1.3.3 version does not. I saw that the ManagerRegistry is deprecated, but which one should I use than in the newer version?

**Comment by alcaeus** [comment]
The problem is that a library that uses the persistence interfaces apparently doesn't handle the new class accordingly. That's nothing to be fixed here, it needs to be fixed downstream.

**Comment by xtrasmal** [comment]
@alcaeus Have you already researched the problem?

**Comment by malarzm** [comment]
@xtrasmal there's nothing we can really investigate on our end.

**Comment by alcaeus** [comment]
@xtrasmal we've had a similar issue with a different framework, see https://github.com/neos/flow-development-collection/pull/1891 for that fix. There's nothing else we can do.

**Comment by xtrasmal** [comment]
@alcaeus @malarzm Thanks for your replies. I quickly looked into it and the problem is actually quite understandable. Frameworks that have some kind of Doctrine adapter or bridge have interfaces that alias ManagerRegistry into the service container(DIC or IOC) of the framework. 
Changing the bootstrapping of the ManagerRegistry will solve those problems.

**Comment by olenchenko-a** [comment]
> @alcaeus @malarzm Thanks for your replies. I quickly looked into it and the problem is actually quite understandable. Frameworks that have some kind of Doctrine adapter or bridge have interfaces that alias ManagerRegistry into the service container(DIC or IOC) of the framework. Changing the bootstrapping of the ManagerRegistry will solve those problems.

Hi, in which way you changed bootstrapig of ManagerRegistry ?
