### ISSUE TITLE
Persistence 1.3 PHP 7.4.1 and preloading

### ISSUE THREAD

**Issue by Avatar4eg** [doctrine/persistence#86]
Upgrading persistence to 1.3 and up on PHP 7.4 with `opcache.preload` lead to `zend_mm_heap corrupted`
Ref: https://bugs.php.net/bug.php?id=78995

**Comment by alcaeus** [comment]
Due to the namespace change coming in 2.0, we need to rely on `class_alias` and `interface_alias` to provide a compatibility layer to avoid a hard BC break that would be hard to manage for consumers. Unfortunately, this doesn't play nice with preloading, as @nikic explained here: https://github.com/doctrine/orm/pull/7953#discussion_r359312375.

This is not something that we can fix in this library.
